version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres.djawbrflcomjlnlrymdv:lKHEKyXzRuCMSqV2@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
